### ISSUE TITLE
Doesn't serve error stylesheet

### ISSUE THREAD

**Issue by Munter** [Munter/fusile#15]
* Read a .scss file
* Add a syntax error to the file
* Read file again

Expected: It should serve a CSS error stylesheet with the error message in content
Actual: Serves cached content, but the amount of bytes served is different than original

**Comment by unwitting** [comment]
I'll look at this as a way of getting into the code, assign it my way if you'd like.

**Comment by Munter** [comment]
Awesome. I've given you push access as well :)

**Comment by Munter** [comment]
I think I'll need to go through the code and comment a bit more. There are a few places where I've skipped explanations that might be needed to understand the problems that are solved

**Comment by unwitting** [comment]
That would be great - I'd been thinking about doing the same myself as I
went.

**Comment by unwitting** [comment]
Do you have objections to some quite a lot more extensive logging in verbose mode?

**Comment by unwitting** [comment]
Reproduced case, css output is:

```css
body {
  background-color: red; }

/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9Vc2Vycy9qYWNrL3RtcC9zcmMvdGVzdC5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUVBO0VBRlEsc0JBQUEsRUFBQSIsImZpbGUiOiJ0by5jc3MifQ== */er: 4px dashed red;
  margin-bottom: 10px;
  content: "Transpiler error: \00002fUsers\00002fjack\00002ftmp\00002fsrc\00002ftest\00002escss:4:30\00000aproperty \000022asasa\000022 must be followed by a \000027:\000027";
}
```

Output from my new logging in 13ae910 is:

```
getattr /
getattr /test.css
getattr /test.css
open /test.css
read pathname /test.css len 65536 offset 0
tolkPromise exists
success from tolkPromise { result: 'body {\n  background-color: red; }\n\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi9Vc2Vycy9qYWNrL3RtcC9zcmMvdGVzdC5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUVBO0VBRlEsc0JBQUEsRUFBQSIsImZpbGUiOiJ0by5jc3MifQ== */',
  imports: [],
  meta:
   { entry: '/Users/jack/tmp/src/test.scss',
     start: 1443622370089,
     end: 1443622370090,
     duration: 1 },
  sourcemap:
   { version: 3,
     file: 'test.css',
     sources: [ '/Users/jack/tmp/src/test.scss' ],
     sourcesContent: [ '$color: red;\n\nbody {\n    background-color: $color;\n}\n' ],
     mappings: 'AAEA;EACI,AAHI',
     names: [] } }
writing slice body {
  background-color: red; }

/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjo
calling back with length 248
read pathname /test.css len 65536 offset 248
tolkPromise exists
Transpiler error: /Users/jack/tmp/src/test.scss:4:30
property "asasa" must be followed by a ':'
success from tolkPromise { result: 'body * {\n  display: none !important;\n}\n\nbody:before {\n  line-height: 1.5;\n  display: block;\n  z-index: 99999999;\n  white-space: pre;\n  font-family: "Courier New", monospace;\n  font-size: 20px;\n  color: black;\n  margin: 10px;\n  padding: 10px;\n  border: 4px dashed red;\n  margin-bottom: 10px;\n  content: "Transpiler error: \\00002fUsers\\00002fjack\\00002ftmp\\00002fsrc\\00002ftest\\00002escss:4:30\\00000aproperty \\000022asasa\\000022 must be followed by a \\000027:\\000027";\n}\n' }
writing slice er: 4px dashed red;
  margin-bottom: 10px;
  content: "Transpiler error: \00002fUsers\00002fjack\000
calling back with length 221
read pathname /test.css len 65536 offset 469
tolkPromise exists
success from tolkPromise { result: 'body * {\n  display: none !important;\n}\n\nbody:before {\n  line-height: 1.5;\n  display: block;\n  z-index: 99999999;\n  white-space: pre;\n  font-family: "Courier New", monospace;\n  font-size: 20px;\n  color: black;\n  margin: 10px;\n  padding: 10px;\n  border: 4px dashed red;\n  margin-bottom: 10px;\n  content: "Transpiler error: \\00002fUsers\\00002fjack\\00002ftmp\\00002fsrc\\00002ftest\\00002escss:4:30\\00000aproperty \\000022asasa\\000022 must be followed by a \\000027:\\000027";\n}\n' }
writing slice
calling back with length 0
release /test.css
```

So what happens is that the cached content of N bytes gets returned, and then on the next read at offset N we get the error CSS and whack it into the buffer as well, which is what ends us up with the concatenated output above.
